project:
  type: website

website:
  title: "Aotumated AHKv2 coinvertor"
  navbar:
    left:
      - HowToUse.qmd
      - about.qmd
      - OrignalReadmeFile.qmd

format:
  html:
    theme: Vapor
    css: styles.css
    toc: true



